# Generated by Django 5.2.1 on 2025-05-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilizator_adauga_produse_alimente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='face_rapoarte',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='vede_rapoarte',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiune', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
