# Generated by Django 5.2.1 on 2025-05-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_utilizator_face_rapoarte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizator',
            name='vede_rapoarte',
        ),
    ]
