# Generated by Django 5.2.1 on 2025-05-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=255)),
                ("locatie", models.CharField(max_length=255)),
                ("tipuri_produse", models.TextField(help_text="Ex: lapte, mezeluri")),
                (
                    "certificari",
                    models.TextField(blank=True, help_text="Ex: ISO 22000, BIO"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ferma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=255)),
                ("locatie", models.CharField(max_length=255)),
                (
                    "tip_ferma",
                    models.CharField(
                        choices=[
                            ("vegetala", "Vegetală"),
                            ("animala", "Animalieră"),
                            ("mixta", "Mixtă"),
                        ],
                        max_length=50,
                    ),
                ),
                ("suprafata_ha", models.FloatField(help_text="Suprafață în hectare")),
                (
                    "tipuri_culturi",
                    models.TextField(blank=True, help_text="Ex: grâu, porumb"),
                ),
                (
                    "tipuri_animale",
                    models.TextField(blank=True, help_text="Ex: vaci, porci"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductieFabrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_productiei", models.DateField()),
                ("produs_final", models.CharField(max_length=100)),
                (
                    "materie_prima",
                    models.TextField(help_text="Tipuri și cantități de materii prime"),
                ),
                ("cantitate_produsa_kg", models.FloatField()),
                ("energie_consumata_kwh", models.FloatField()),
                ("deseuri_generate_kg", models.FloatField()),
                (
                    "fabrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fabrica"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductieFerma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_recoltarii", models.DateField()),
                ("tip_produs", models.CharField(max_length=100)),
                ("cantitate_kg", models.FloatField()),
                ("fertilizatori", models.TextField(blank=True)),
                ("pesticide", models.TextField(blank=True)),
                ("tip_irigatie", models.CharField(blank=True, max_length=100)),
                ("consum_apa_litri", models.FloatField(blank=True, null=True)),
                (
                    "ferma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.ferma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCalitate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produs", models.CharField(max_length=100)),
                ("data_testului", models.DateField()),
                ("rezultat_microbiologic", models.CharField(max_length=255)),
                (
                    "valori_nutritionale",
                    models.TextField(help_text="Ex: calorii, proteine, grăsimi"),
                ),
                ("data_expirarii", models.DateField()),
                ("neconformitati", models.TextField(blank=True)),
                (
                    "fabrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fabrica"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DataEntry",
        ),
        migrations.DeleteModel(
            name="Farm",
        ),
        migrations.DeleteModel(
            name="FoodFactory",
        ),
    ]
