# Generated by Django 5.2.1 on 2025-05-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCalitate',
            new_name='TestCalitateFabrica',
        ),
        migrations.RenameField(
            model_name='testcalitatefabrica',
            old_name='data_testului',
            new_name='data_test',
        ),
        migrations.CreateModel(
            name='TestCalitateFerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliment', models.CharField(max_length=100)),
                ('data_testului', models.DateField()),
                ('rezultat_microbiologic', models.CharField(max_length=255)),
                ('valori_nutritionale', models.TextField(help_text='Ex: calorii, proteine, grăsimi')),
                ('data_expirarii', models.DateField()),
                ('neconformitati', models.TextField(blank=True)),
                ('ferma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ferma')),
            ],
        ),
    ]
